### ISSUE TITLE
Invalid checksum

### ISSUE THREAD

**Issue by fzzzy** [fzzzy/el-stacko#1]
"React attempted to use reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server."

**Comment by ianb** [comment]
http://stackoverflow.com/questions/26172393/reactjs-invalid-checksum suggests render to the exact element
